services:
  - type: web
    name: tendajatim
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: CI_ENVIRONMENT
        value: production
      - key: DATABASE_URL
        sync: false
