databases:
  - name: tendajatim-db
    databaseName: tendajatim
    user: tendajatim
    plan: basic-256mb
    region: singapore

services:
  - type: web
    name: tendajatim
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: CI_ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: tendajatim-db
          property: connectionString
