<?php $errors = session()->getFlashdata('errors') ?? []; $staffAccount ??= null; $position = strtolower(old('position', $employee['position'] ?? '')); $position = in_array($position, ['staff', 'admin'], true) ? $position : ''; ?>
<div class="form-panel"><div class="panel-heading"><div><h2>Informasi pegawai</h2><p class="muted">Isi identitas pegawai.</p></div><a class="text-link" href="<?= site_url('employees') ?>">← Kembali</a></div>
<?php if ($errors): ?><div class="alert alert-error"><?php foreach ($errors as $error): ?><div><?= esc($error) ?></div><?php endforeach ?></div><?php endif ?>
<form method="post" action="<?= $employee ? site_url('employees/' . $employee['id']) : site_url('employees') ?>" class="form-grid"><?= csrf_field() ?>
    <label>Nama lengkap *<input name="name" value="<?= esc(old('name', $employee['name'] ?? '')) ?>" required maxlength="120"></label><label>Nomor telepon<input name="phone" value="<?= esc(old('phone', $employee['phone'] ?? '')) ?>" maxlength="30"></label><label>Jabatan *<select name="position" required><option value="" disabled <?= $position === '' ? 'selected' : '' ?>>Pilih jabatan</option><option value="staff" <?= $position === 'staff' ? 'selected' : '' ?>>Staff</option><option value="admin" <?= $position === 'admin' ? 'selected' : '' ?>>Admin</option></select></label>
    <div class="full-width account-section"><h3>Akun login Staff <span class="badge badge-unrecorded">Opsional</span></h3><p class="muted">Akun ini hanya bisa melihat dan mencatat absensi milik pegawai ini. Kata sandi minimal 12 karakter.</p>
        <?php if ($staffAccount): ?><p class="account-existing">Akun aktif: <strong><?= esc($staffAccount['username']) ?></strong>. Isi kata sandi baru hanya jika ingin meresetnya.</p><?php endif ?>
        <div class="form-grid account-grid"><label>Nama pengguna<input name="staff_username" value="<?= esc(old('staff_username', $staffAccount['username'] ?? '')) ?>" minlength="4" maxlength="60" autocomplete="off"><small>Huruf dan angka saja.</small></label><label><?= $staffAccount ? 'Reset kata sandi' : 'Kata sandi Staff' ?><input type="password" name="staff_password" minlength="12" maxlength="128" autocomplete="new-password"><small><?= $staffAccount ? 'Biarkan kosong untuk mempertahankan kata sandi.' : 'Kosongkan nama pengguna dan kata sandi bila belum perlu login.' ?></small></label></div>
    </div>
    <?php if ($employee): ?><label>Status<select name="is_active"><option value="1" <?= old('is_active', (string) $employee['is_active']) === '1' ? 'selected' : '' ?>>Aktif</option><option value="0" <?= old('is_active', (string) $employee['is_active']) === '0' ? 'selected' : '' ?>>Nonaktif</option></select></label><?php endif ?>
    <div class="form-actions"><button class="btn btn-primary">Simpan pegawai</button><a class="btn btn-plain" href="<?= site_url('employees') ?>">Batal</a></div>
</form></div>
